import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "fi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    members: "Members",
    partners: "Partners",
    howItWorks: "How It Works",
    about: "About",
    blog: "Blog",
    campaign: "Campaign",
    letsGo: "Let's Go",
    updateBanner: "Website is under update",
    heroHeadline: "50% Off Everything",
    heroSubhead: "AI-powered discounts that actually work",
    heroText: "Join thousands who've cracked the code to smart spending.",
    heroDiscountRate: "Discount Rate",
    heroPartners: "Partners",
    heroSaved: "Saved",
    partnerUp: "Partner Up (We're Cool Like That)",
    // Members page
    membersHero: "Join 10K+ Legends Who",
    membersHeroSub: "Never Pay Sucker Prices",
    membersHeroDesc: "Welcome to the club where paying full price is basically illegal. Our AI is literally smarter than your ex and finds you deals that'll make your wallet do a happy dance.",
    startSaving: "Start Saving Now",
    becomePartner: "Become a Partner",
    happyMembers: "Happy Members",
    avgSavings: "Average Savings",
    avgAnnualSavings: "Avg Annual Savings",
    partnerOutlets: "Partner Outlets",
    whyLoveUs: "Why You'll Love Us",
    perksThatSlap: "Perks That Actually Slap",
    perksDesc: "We're not just another discount app - we're your financial wingman with benefits that pay for themselves faster than you can say 'broke no more'.",
    unlimitedDiscounts: "Unlimited 'Hell Yeah' Discounts",
    unlimitedDiscountsDesc: "500+ spots where you flex that 50% savings like the financial genius you are",
    aiNotDumb: "AI That's Not Dumb",
    aiNotDumbDesc: "Unlike other apps, our AI actually reads the room and serves recommendations that don't suck",
    vipTreatment: "VIP Treatment (For Real)",
    vipTreatmentDesc: "Cut the line, skip the peasants, get first access to the good stuff before it's cool",
    supportDamn: "Support That Gives a Damn",
    supportDamnDesc: "Real humans who actually solve problems instead of copy-pasting 'have you tried turning it off'",
    pricingTitle: "Pricing That Won't Rob You",
    pricingDesc: "Two options: save money monthly or save even more money yearly. Either way, you're winning at life.",
    monthlyFlex: "Monthly Flex",
    annualPower: "Annual Power Move",
    bestValue: "Best Value",
    perMonth: "/month",
    perYear: "/year",
    saveAnnually: "Save €52.6 annually",
    joinNow: "Join Now",
    cancelAnytime: "Cancel anytime",
    monthsFree: "2 months FREE bonus",
    bothPlans: "Both plans include:",
    bothPlansDesc: "All premium features, unlimited discounts, AI recommendations, priority support, and access to exclusive partners.",
    noHiddenFees: "No hidden fees • Cancel anytime • 30-day money-back guarantee",
    memberStories: "Member Stories",
    realMembers: "Real Members, Real Savings",
    realMembersDesc: "See how our community is saving thousands while living their best life.",
    exclusiveFeatures: "Exclusive Features",
    membersOnlyPerks: "Members-Only Perks",
    membersOnlyPerksDesc: "Access features that regular users can only dream about.",
    earlyAccess: "Early Access to New Partners",
    earlyAccessDesc: "Be the first to discover new restaurants, shops, and services before they're available to the public",
    exclusiveEvents: "Exclusive Member Events",
    exclusiveEventsDesc: "VIP events, networking opportunities, and special experiences designed just for our community",
    limitedOffers: "Limited-Time Member Offers",
    limitedOffersDesc: "Flash sales, bonus discounts, and seasonal promotions exclusive to members",
    faqTitle: "FAQ",
    faqHeading: "Got Questions? We Got Answers",
    faqQ1: "Can I bail if I want?",
    faqA1: "Duh! Cancel whenever you want, no guilt trips or weird exit surveys. We're not your clingy ex.",
    faqQ2: "How does this magic work?",
    faqA2: "Flash that Bargn membership like the VIP you are. Boom - 50% off instantly. No coupons, no hassle, no cap.",
    faqQ3: "Am I trapped in a contract?",
    faqA3: "Hell no! We're not a gym membership. Month-to-month or yearly - your choice. Cancel whenever, we'll still be friends.",
    ctaHeading: "Ready to Graduate From Broke?",
    ctaDesc: "Join the club where paying full price is for beginners. Your future self (and bank account) will literally thank you.",
    // About page
    "about.hero.badge": "MEET THE REBELS",
    "about.hero.headline1": "We're Not Your",
    "about.hero.headline2": "Average",
    "about.hero.headline3": "Discount App",
    "about.hero.subtext": "We're the rebels who said 'nah' to paying full price and built an AI that actually gets you. No cap, we're literally changing how people save money.",
    "about.hero.cta1": "Let's Go",
    "about.hero.cta2": "Join The Squad",
    "about.story.badge": "Our Story",
    "about.story.headline": "Started From The Bottom, Now We're... Still Broke But With Better Deals",
    "about.story.text": "Founded in 2023 by a group of Gen Z entrepreneurs who were tired of being financially drained by overpriced everything. We looked at the discount space and thought 'this is giving boomer energy' - so we decided to fix it with AI that doesn't suck.",
    "about.story.founded": "Founded 2023",
    "about.story.tagline": "Disrupting Discounts",
    "about.mission.badge": "Our Mission",
    "about.mission.headline": "Making Full Price Extinct",
    "about.mission.text": "Our mission is simple: use AI to connect people with 50% discounts on everything they actually want. No more random coupons for stuff you'll never use. We're creating a world where paying full price feels illegal.",
    "about.mission.card1.title": "50%",
    "about.mission.card1.desc": "Average Discount on Every Purchase",
    "about.mission.card2.title": "AI-Powered",
    "about.mission.card2.desc": "Personalized Recommendations That Actually Work",
    "about.mission.card3.title": "Zero Fees",
    "about.mission.card3.desc": "No Hidden Charges, Just Pure Savings",
    "about.values.badge": "Our Values",
    "about.values.headline": "What We Stand For",
    "about.values.subtext": "These aren't just words on a wall. They're the principles we live by every single day.",
    "about.values.card1.title": "Innovation That Slaps",
    "about.values.card1.desc": "We use cutting-edge AI because why settle for basic algorithms when you can have ones that understand your vibe?",
    "about.values.card2.title": "No Cap Policy",
    "about.values.card2.desc": "We're transparent about everything - fees, partnerships, how our AI works. No hidden agenda, just straight facts.",
    "about.values.card3.title": "Community First",
    "about.values.card3.desc": "Our users aren't customers, they're family. We build for the community, not just the algorithm.",
    "about.team.badge": "Meet The Squad",
    "about.team.headline": "The Humans Behind The Magic",
    "about.team.subtext": "We're a diverse team of innovators, dreamers, and deal-hunters who believe technology should make life better, not more complicated.",
    "about.team.member1.name": "Alex Chen",
    "about.team.member1.role": "Founder & CEO",
    "about.team.member1.bio": "The visionary who said 'enough' to full prices",
    "about.team.member2.name": "Sarah Kim",
    "about.team.member2.role": "Chief Technology Officer",
    "about.team.member2.bio": "Codes magic and makes servers dance",
    "about.team.member3.name": "Marcus Johnson",
    "about.team.member3.role": "AI Engineering Lead",
    "about.team.member3.bio": "Teaches AI to understand your vibe",
    "about.team.member4.name": "Emma Rodriguez",
    "about.team.member4.role": "Head of Growth",
    "about.team.member4.bio": "Spreads the word about saving money",
    "about.team.cta": "Join Our Team",
    "about.cta.headline": "Ready to Join the Revolution?",
    "about.cta.subtext": "Become part of a movement that's changing how people save money. No cap, just results.",
    "about.cta.button1": "Let's Go",
    "about.cta.button2": "Join The Squad",
    // How It Works page
    "how.badge": "STEP-BY-STEP GUIDE",
    "how.hero.headline": "Save 50% Without Selling Your Soul",
    "how.hero.description": "Look, we get it. You're broke but bougie. We've made saving money so stupidly simple, even your tech-challenged aunt could figure it out. No PhD in couponing required.",
    "how.timeline.label": "Idiot-Proof Guide",
    "how.timeline.heading": "Your Journey from Broke to Woke",
    "how.timeline.subheading": "Follow these 5 braindead-simple steps and start flexing those savings. Seriously, if you mess this up, we can't help you.",
    "how.step1.title": "Download & Don't Cry",
    "how.step1.description": "Download our app faster than you swipe left on dating apps. Pick a plan, pay up, and boom – you're officially part of the savings mafia.",
    "how.step1.bullet1": "Download from App Store or Google Play",
    "how.step1.bullet2": "Choose monthly or yearly plan",
    "how.step2.title": "Stalk Our Partners (Legally)",
    "how.step2.description": "Use our creepy-good AI map to find 500+ places near you that actually want to give you money off. It's like Tinder, but for your wallet.",
    "how.step2.bullet1": "Browse 500+ partner locations",
    "how.step2.bullet2": "Filter by category and distance",
    "how.step3.title": "Swipe Right on Savings",
    "how.step3.description": "Browse deals like you browse memes – mindlessly but with purpose. Swipe to activate that sweet 50% off. Our AI stalks your preferences (in a good way).",
    "how.step3.bullet1": "Swipe to activate instant deals",
    "how.step3.bullet2": "AI learns your preferences",
    "how.step4.title": "Flash That Digital Bling",
    "how.step4.description": "Show your phone to the staff like you're some VIP hotshot. They'll verify you're legit and not some discount fraud artist.",
    "how.step4.bullet1": "Show activated deal to staff",
    "how.step4.bullet2": "Instant verification & approval",
    "how.step5.title": "Pay Half, Feel Whole",
    "how.step5.description": "Hand over 50% of what you normally would and walk away like the financial genius you are. Rate the experience so our AI gets even creepier at knowing what you want.",
    "how.step5.bullet1": "Pay only 50% of original price",
    "how.step5.bullet2": "Rate experience for better AI",
    "how.why.label": "Why We're Not Idiots",
    "how.why.heading": "Designed by Lazy People, for Lazy People",
    "how.why.description": "We hate complicated stuff as much as you do. So we made this so simple, it's basically insulting to your intelligence.",
    "how.benefit1.title": "Zero Brain Cells Required",
    "how.benefit1.description": "No scissors for coupons, no memory palace for codes, no calendar alerts for expiry dates. Just instant gratification for your shopping addiction.",
    "how.benefit2.title": "Faster Than Your Ex's Rebound",
    "how.benefit2.description": "Activate discounts quicker than you can say 'financial responsibility.' No waiting around like you're at the DMV.",
    "how.benefit3.title": "AI That Actually Gets You",
    "how.benefit3.description": "Our AI learns your taste better than your therapist learns your trauma. It'll suggest deals you actually want, not random junk.",
    // Partners page
    "partners.hero.badge": "BUSINESS PARTNERSHIP",
    "partners.hero.headline1": "500+ Businesses",
    "partners.hero.headline2": "Can't Be Wrong",
    "partners.hero.subheadline": "(But Your Competition Might Be)",
    "partners.hero.body": "Look, while your competitors are still paying hefty commissions and begging for customers, our partners are laughing all the way to the bank. Zero fees, maximum flex, and customers who actually want to be there. Revolutionary? Nah. Common sense? Absolutely.",
    "partners.hero.cta.primary": "Apply Now",
    "partners.hero.cta.secondary": "Join as Member",
    "partners.stats.activePartners": "Active Partners",
    "partners.stats.commissionFees": "Commission Fees",
    "partners.stats.avgIncrease": "Avg Customer Increase",
    "partners.stats.qualityMembers": "Quality Members",
    "partners.signup.badge": "Quick Start",
    "partners.signup.headline": "Sign Up Now - No Applications!",
    "partners.signup.subheadline": "Create your business account instantly and start onboarding immediately. No waiting, no lengthy approval process.",
    "partners.signup.steps.step1.title": "Create Account",
    "partners.signup.steps.step1.description": "Sign up instantly with your business email and basic info",
    "partners.signup.steps.step1.duration": "Takes 2 minutes",
    "partners.signup.steps.step2.title": "Set Your 50% Offers",
    "partners.signup.steps.step2.description": "Choose which services get 50% discount (3x per year per customer)",
    "partners.signup.steps.step2.action": "Define your offers",
    "partners.signup.steps.step3.title": "Go Live",
    "partners.signup.steps.step3.description": "Add photos, menu, logo. Quick verification, then live!",
    "partners.signup.steps.step3.action": "Start receiving customers",
    "partners.signup.form.venueName": "Venue Name",
    "partners.signup.form.venueNamePlaceholder": "Your business name",
    "partners.signup.form.city": "City",
    "partners.signup.form.cityPlaceholder": "Where are you located?",
    "partners.signup.form.email": "Email",
    "partners.signup.form.emailPlaceholder": "Business email address",
    "partners.signup.form.button": "Apply Now",
    "partners.signup.form.validation": "Please fill in all fields",
    "partners.signup.form.success": "Application submitted! We'll be in touch soon.",
    "partners.signup.benefits.noApplication": "No Application Required",
    "partners.signup.benefits.instantSetup": "Instant Setup",
    "partners.signup.benefits.zeroCommission": "Zero Commission",
    "partners.comparison.badge": "The Math",
    "partners.comparison.headline": "The Numbers Don't Lie",
    "partners.comparison.subheadline": "See exactly how much more you keep with Bargn vs traditional platforms. Spoiler: It's a lot.",
    "partners.comparison.transactionValue": "Transaction Value",
    "partners.comparison.transactionHelper": "Adjust to see your potential earnings",
    "partners.comparison.platformCommission": "Platform Commission",
    "partners.comparison.commissionHelper": "Typical range: 25-45%",
    "partners.comparison.traditional.title": "Traditional Platforms",
    "partners.comparison.traditional.subtitle": "UberEats, Wolt, etc.",
    "partners.comparison.bargn.title": "Bargn",
    "partners.comparison.bargn.subtitle": "Zero Commission, Maximum Profit",
    "partners.comparison.originalPrice": "Original Price",
    "partners.comparison.customerPays": "Customer Pays",
    "partners.comparison.off": "off",
    "partners.comparison.revenue": "Your Revenue",
    "partners.comparison.platformTakes": "Platform Takes",
    "partners.comparison.bargnTakes": "Bargn Takes",
    "partners.comparison.youKeep": "You Keep",
    "partners.comparison.margin": "profit margin",
    "partners.comparison.difference.title": "Your Advantage with Bargn",
    "partners.comparison.difference.extraRevenue": "Extra Revenue Per Transaction",
    "partners.comparison.difference.moreProfit": "More Profit",
    "partners.comparison.difference.description": "Per transaction. Multiply this by hundreds of customers per month.",
  },
  fi: {
    home: "Koti",
    members: "Jäsenet",
    partners: "Kumppanit",
    howItWorks: "Miten Se Toimii",
    about: "Tietoa",
    blog: "Blogi",
    campaign: "Kampanja",
    letsGo: "Aloitetaan",
    updateBanner: "Verkkosivusto päivitetään",
    heroHeadline: "50% Alennus Kaikesta",
    heroSubhead: "AI-vetoisia alennuksia jotka oikeesti toimii",
    heroText: "Liity tuhansien joukkoon jotka on crackannu koodin fiksun kuluttamisen.",
    heroDiscountRate: "Alennusprosentti",
    heroPartners: "Kumppania",
    heroSaved: "Säästetty",
    partnerUp: "Kumppani (Ollaan Cooli Sillä Tavalla)",
    // Members page
    membersHero: "Liity 10K+ Legendaan",
    membersHeroSub: "Ei Ikinä Maksa Mulkku Hintoja",
    membersHeroDesc: "Tervetuloa klubiin missä täyden hinnan maksaminen on periaatteessa laitonta. Meidän AI on kirjaimellisesti fiksumpi kun sun ex ja löytää sulle diilejä jotka saa sun lompakon tanssimaan.",
    startSaving: "Aloita Säästäminen",
    becomePartner: "Ryhdy Kumppaniksi",
    happyMembers: "Tyytyväistä Jäsentä",
    avgSavings: "Keskisäästöt",
    avgAnnualSavings: "Keskim. Vuosisäästöt",
    partnerOutlets: "Kumppanipaikkoja",
    whyLoveUs: "Miksi Rakastut Meihin",
    perksThatSlap: "Edut Jotka Oikeesti Slappaa",
    perksDesc: "Me ei olla vaan joku random alennusappi - me ollaan sun taloudellinen wingman eduilla jotka maksaa ittensä takasin nopeemmin ku ehdit sanoo 'oon rikki'.",
    unlimitedDiscounts: "Rajattomat 'Vittu Joo' Alennukset",
    unlimitedDiscountsDesc: "500+ paikkaa missä voit flexaa sitä 50% säästöö niinku se talousnero mitä oot",
    aiNotDumb: "AI Joka Ei Oo Tyhmä",
    aiNotDumbDesc: "Toisin ku muut apit, meidän AI oikeesti lukee tilanteen ja tarjoilee suosituksia jotka ei imu",
    vipTreatment: "VIP Kohtelu (Oikeesti)",
    vipTreatmentDesc: "Ohita jono, skipppaa köyhät, saat ensipääsyn parhaaseen kamaan ennenku se on coolia",
    supportDamn: "Tuki Joka Välittää",
    supportDamnDesc: "Oikeita ihmisiä jotka oikeesti ratkoo ongelmia sen sijaan et copypasteis 'ootko koittanu sammuttaa sen'",
    pricingTitle: "Hinnoittelu Joka Ei Ryöstä Sua",
    pricingDesc: "Kaks vaihtoehtoo: säästä rahaa kuukausittain tai säästä vielä enemmän vuosittain. Kumminki voitat elämässä.",
    monthlyFlex: "Kuukausittainen Flexaus",
    annualPower: "Vuosittainen Power Move",
    bestValue: "Paras Tarjous",
    perMonth: "/kk",
    perYear: "/vuosi",
    saveAnnually: "Säästä €52.6 vuodessa",
    joinNow: "Liity Nyt",
    cancelAnytime: "Peruuta koska vaan",
    monthsFree: "2 kuukautta ILMAISEKS bonuksena",
    bothPlans: "Molemmat suunnitelmat sisältää:",
    bothPlansDesc: "Kaikki premium ominaisuudet, rajattomat alennukset, AI suositukset, priority tuki, ja pääsy eksklusiivisiin kumppaneihin.",
    noHiddenFees: "Ei piilomaksuja • Peruuta koska vaan • 30 päivän rahat takas -takuu",
    memberStories: "Jäsentarinoita",
    realMembers: "Oikeita Jäseniä, Oikeita Säästöjä",
    realMembersDesc: "Katso miten meidän yhteisö säästää tuhansia samalla ku elää parasta elämäänsä.",
    exclusiveFeatures: "Eksklusiiviset Ominaisuudet",
    membersOnlyPerks: "Vain Jäsenille -Edut",
    membersOnlyPerksDesc: "Pääsy ominaisuuksiin joista tavalliset käyttäjät voi vaan unelmoida.",
    earlyAccess: "Ennakko-oikeus Uusiin Kumppaneihin",
    earlyAccessDesc: "Ole eka joka löytää uudet ravintolat, kaupat ja palvelut ennenku ne on julkisesti saatavilla",
    exclusiveEvents: "Eksklusiiviset Jäsentapahtumat",
    exclusiveEventsDesc: "VIP tapahtumat, verkostoitumismahdollisuudet ja erikoiskokemuksia suunniteltu vaan meidän yhteisölle",
    limitedOffers: "Rajoitetun Ajan Jäsentarjoukset",
    limitedOffersDesc: "Flash myynti, bonusalennukset ja kausi-kampanjat vaan jäsenille",
    faqTitle: "UKK",
    faqHeading: "Sul On Kysymyksiä? Meil On Vastauksia",
    faqQ1: "Voinks bailaa jos haluan?",
    faqA1: "Duh! Peruuta koska vaan, ei syyllisyysrippei tai outoja exit kyselyjä. Me ei olla sun tahmee ex.",
    faqQ2: "Miten tää taika toimii?",
    faqA2: "Flashaa toi Bargn jäsenyys niinku se VIP mitä oot. Boom - 50% alennust heti. Ei kuponkeja, ei häslingii, ei cap.",
    faqQ3: "Olenko loukkus sopimuksessa?",
    faqA3: "Helvetti ei! Me ei olla kuntosalijäsenyys. Kuukausittain tai vuosittain - sun valinta. Peruuta milloin vaan, ollaan silti kavereita.",
    ctaHeading: "Valmiina Valmistumaan Köyhyydestä?",
    ctaDesc: "Liity klubiin missä täyden hinnan maksaminen on aloittelijoille. Sun tuleva minä (ja pankkitili) kiittää sua kirjaimellisesti.",
    // About page
    "about.hero.badge": "MEET THE REBELS",
    "about.hero.headline1": "Me Ei Olla Sun",
    "about.hero.headline2": "Tavallinen",
    "about.hero.headline3": "Alennussovellus",
    "about.hero.subtext": "Me ollaan ne kapinalliset jotka sanoi 'nah' täyden hinnan maksulle ja rakensettiin AI joka oikeesti ymmärtää sut. No cap, me muutetaan literally miten ihmiset säästää rahaa.",
    "about.hero.cta1": "Aloitetaan",
    "about.hero.cta2": "Liity Tiimiin",
    "about.story.badge": "Meidän Tarina",
    "about.story.headline": "Alotettiin Pohjalta, Nyt Ollaan... Vielä Köyhiä Mut Paremmilla Diileillä",
    "about.story.text": "Perustettu 2023 Gen Z yrittäjien porukalla jotka oli väsyneitä siihen et joka ikinen asia on liian kallista. Me katsottiin alennusbisnestä ja ajateltiin 'tää on boomeri energiaa' - ni me päätettiin korjata se AI:lla joka ei ime.",
    "about.story.founded": "Perustettu 2023",
    "about.story.tagline": "Disruptoidaan Alennukset",
    "about.mission.badge": "Meidän Missio",
    "about.mission.headline": "Tehdään Täydestä Hinnasta Sukupuuttoon Kuollut",
    "about.mission.text": "Meidän missio on yksinkertanen: käytetään AI:ta yhdistääksemme ihmisiä 50% alennuksiin kaikesta mitä ne oikeesti haluu. Ei enää randomeja kuponkeja tavaralle mitä et ikinä käytä. Me luodaan maailma missä täyden hinnan maksaminen tuntuu laittomalta.",
    "about.mission.card1.title": "50%",
    "about.mission.card1.desc": "Keskialennust Jokaisesta Ostoksesta",
    "about.mission.card2.title": "AI-Käyttöinen",
    "about.mission.card2.desc": "Personoituja Suosituksia Jotka Oikeesti Toimii",
    "about.mission.card3.title": "Nolla Maksuja",
    "about.mission.card3.desc": "Ei Piilomaksuja, Vaan Puhasta Säästöö",
    "about.values.badge": "Meidän Arvot",
    "about.values.headline": "Mitä Me Edustetaan",
    "about.values.subtext": "Nää ei oo vaan sanoja seinällä. Nää on periaatteita joita me eletään joka ikinen päivä.",
    "about.values.card1.title": "Innovaatio Joka Läjää",
    "about.values.card1.desc": "Me käytetään huippuluokan AI:ta koska miks tyytys perus algoritmeihin ku voit saada sellasia jotka ymmärtää sun viben?",
    "about.values.card2.title": "No Cap Politiikka",
    "about.values.card2.desc": "Ollaan läpinäkyviä kaikesta - maksut, kumppanuudet, miten meidän AI toimii. Ei piiloteltua agendaa, vaan suoria faktoja.",
    "about.values.card3.title": "Yhteisö Ekana",
    "about.values.card3.desc": "Meidän käyttäjät ei oo asiakkaita, ne on perhettä. Me rakennetaan yhteisölle, ei pelkälle algoritmille.",
    "about.team.badge": "Meet The Squad",
    "about.team.headline": "Ihmiset Magian Takana",
    "about.team.subtext": "Me ollaan monipuolinen tiimi innovoijia, unelmoijia ja diilimetsästäjiä jotka uskoo et teknologian pitäis tehä elämästä parempaa, ei monimutkasempaa.",
    "about.team.member1.name": "Alex Chen",
    "about.team.member1.role": "Perustaja & CEO",
    "about.team.member1.bio": "Visionääri joka sano 'tarpeeks' täysille hinnoille",
    "about.team.member2.name": "Sarah Kim",
    "about.team.member2.role": "Teknologiajohtaja",
    "about.team.member2.bio": "Koodaa taikuutta ja saa palvelimet tanssimaan",
    "about.team.member3.name": "Marcus Johnson",
    "about.team.member3.role": "AI-Insinöörijohtaja",
    "about.team.member3.bio": "Opettaa AI:ta ymmärtämään sun viben",
    "about.team.member4.name": "Emma Rodriguez",
    "about.team.member4.role": "Kasvujohtaja",
    "about.team.member4.bio": "Levittää sanaa rahojen säästämisestä",
    "about.team.cta": "Liity Tiimiin",
    "about.cta.headline": "Valmiina Liittymään Vallankumoukseen?",
    "about.cta.subtext": "Tuu osaksi liikettä joka muuttaa miten ihmiset säästää rahaa. Ei cap, vaan tuloksia.",
    "about.cta.button1": "Aloitetaan",
    "about.cta.button2": "Liity Tiimiin",
    // How It Works page
    "how.badge": "VAIHE VAIHEELTA OPAS",
    "how.hero.headline": "Säästä 50% Ilman Sielun Myymistä",
    "how.hero.description": "Katso, me snapataan. Oot köyhä mut bougie. Me tehty rahojen säästämisestä niin typerän yksinkertaista, et jopa sun tekniikka-haastava täti vois oppia sen. Ei PhD kuponkeiluun vaadita.",
    "how.timeline.label": "Idiootti-Varma Opas",
    "how.timeline.heading": "Sun Matka Köyhästä Rikkaaks",
    "how.timeline.subheading": "Seuraa näitä 5 aivo-kuollutta askeletta ja ala flexaa noita säästöjä. Oikeesti, jos mokat tän, me ei voida auttaa sua.",
    "how.step1.title": "Lataa & Älä Itke",
    "how.step1.description": "Lataa appi nopeemmin ku swippaat vasemmalle treffiapeissa. Valitse suunnitelma, maksa, ja boom - oot virallisesti osa säästömaffiaa.",
    "how.step1.bullet1": "Lataa App Storesta tai Google Playsta",
    "how.step1.bullet2": "Valitse kuukausi- tai vuosisuunnitelma",
    "how.step2.title": "Stalkaa Kumppaneita (Laillisesti)",
    "how.step2.description": "Käytä meidän creepy-hyvää AI karttaa löytääksesi 500+ paikkaa lähellä sua jotka oikeesti haluu antaa sulle rahaa pois. Se on niinku Tinder, mut sun lompakolle.",
    "how.step2.bullet1": "Selaa 500+ kumppanipaikkaa",
    "how.step2.bullet2": "Filtteröi kategorian ja etäisyyden mukaan",
    "how.step3.title": "Swaippaa Oikealle Säästöjen Kanssa",
    "how.step3.description": "Selaa diilejä niinku selaat meemejä - ajattelemattomasti mut tarkoituksella. Swaippaa aktivoidaksesi sen swagin 50% alennuksen. Meidän AI stalkkaa sun mieltymyksiä (hyvällä tavalla).",
    "how.step3.bullet1": "Swaippaa aktivoidaksesi instant diilit",
    "how.step3.bullet2": "AI oppii sun mieltymykset",
    "how.step4.title": "Väläytä Sitä Digitaalista Blingiä",
    "how.step4.description": "Näytä puhelin henkilökunnalle niinku oisit joku VIP hotshot. Ne varmistaa et oot legit eikä joku alennushuijari.",
    "how.step4.bullet1": "Näytä aktivoitu diili henkilökunnalle",
    "how.step4.bullet2": "Instant verificointi & hyväksyntä",
    "how.step5.title": "Maksa Puolet, Tunne Itsesi Kokonaiseksi",
    "how.step5.description": "Anna 50% siitä mitä normaalisti antasit ja kävele pois niinku se talousnero mitä oot. Arvioi kokemus ni meidän AI menee vielä creepimmäks siinä tietämisessä mitä haluat.",
    "how.step5.bullet1": "Maksa vaan 50% alkuperäisestä hinnasta",
    "how.step5.bullet2": "Arvioi kokemus parempaa AI:ta varten",
    "how.why.label": "Miksi Me Ei Olla Idiootteja",
    "how.why.heading": "Suunniteltu Laiskoja Ihmisiä Varten, Laiskoille Ihmisille",
    "how.why.description": "Me vihataan monimutkaisia juttuja yhtä paljon ku säkin. Ni me tehtiin tää niin yksinkertaseks, et se on periaatteessa loukkaus sun älykkyydelle.",
    "how.benefit1.title": "Nolla Aivosoluja Vaadita",
    "how.benefit1.description": "Ei saksia kupongeille, ei muistipalatsii koodeille, ei kalenterimuistutuksii vanhentumisvuosille. Vaan instant tyydytystä sun shoppailiriippuvuudelle.",
    "how.benefit2.title": "Nopeempi Ku Sun Exän Rebound",
    "how.benefit2.description": "Aktivoi alennukset nopeemmin ku ehdit sanoo 'taloudellinen vastuu.' Ei odottelua niinku oisit jossain DMV:ssä.",
    "how.benefit3.title": "AI Joka Oikeesti Ymmärtää Sut",
    "how.benefit3.description": "Meidän AI oppii sun maun paremmin ku sun terapeutti oppii sun traumat. Se ehdottaa diilejä mitä oikeesti haluat, ei randomii krääsää.",
    // Partners page
    "partners.hero.badge": "BISNESKUMPPANUUS",
    "partners.hero.headline1": "500+ Bisnestä",
    "partners.hero.headline2": "Ei Voi Olla Väärässä",
    "partners.hero.subheadline": "(Mut Sun Kilpailijat Voi Olla)",
    "partners.hero.body": "Katso, ku sun kilpailijat vieläki maksaa isoja provisioita ja kerjää asiakkaita, meidän kumppanit nauraa matkalla pankkiin. Nolla kuluja, maksimi flexausta, ja asiakkaat ketkä oikeesti haluu olla siellä. Vallankumouksellista? Nah. Järki? Ihan täysin.",
    "partners.hero.cta.primary": "Hae Nyt",
    "partners.hero.cta.secondary": "Liity Jäseneksi",
    "partners.stats.activePartners": "Aktiivista Kumppania",
    "partners.stats.commissionFees": "Provisiomaksut",
    "partners.stats.avgIncrease": "Keskim. Kasvu",
    "partners.stats.qualityMembers": "Laadukkaita Jäseniä",
    "partners.signup.badge": "Nopea Startti",
    "partners.signup.headline": "Kirjaudu Nyt - Ei Hakemuksia!",
    "partners.signup.subheadline": "Luo bisnestilisi heti ja aloita onboarding välittömästi. Ei odottelua, ei pitkää hyväksymisprosessia.",
    "partners.signup.steps.step1.title": "Luo Tili",
    "partners.signup.steps.step1.description": "Kirjaudu heti bisnessähköpostilla ja perustiedoilla",
    "partners.signup.steps.step1.duration": "Vie 2 minuuttii",
    "partners.signup.steps.step2.title": "Aseta 50% Tarjoukset",
    "partners.signup.steps.step2.description": "Valitse mitkä palvelut saa 50% alennuksen (3x vuodessa per asiakas)",
    "partners.signup.steps.step2.action": "Määrittele tarjouksesi",
    "partners.signup.steps.step3.title": "Go Live",
    "partners.signup.steps.step3.description": "Lisää kuvat, menu, logo. Nopee verificointi, sit live!",
    "partners.signup.steps.step3.action": "Aloita asiakkaiden vastaanotto",
    "partners.signup.form.venueName": "Paikan Nimi",
    "partners.signup.form.venueNamePlaceholder": "Sun bisnesnimi",
    "partners.signup.form.city": "Kaupunki",
    "partners.signup.form.cityPlaceholder": "Missä sijaitset?",
    "partners.signup.form.email": "Sähköposti",
    "partners.signup.form.emailPlaceholder": "Bisnes-sähköpostiosoite",
    "partners.signup.form.button": "Hae Nyt",
    "partners.signup.form.validation": "Täytä kaikki kentät",
    "partners.signup.form.success": "Hakemus lähetetty! Ollaan yhteydessä pian.",
    "partners.signup.benefits.noApplication": "Ei Hakemusta Vaadita",
    "partners.signup.benefits.instantSetup": "Välitön Setuppi",
    "partners.signup.benefits.zeroCommission": "Nolla Provisiota",
    "partners.comparison.badge": "Matikka",
    "partners.comparison.headline": "Numerot Ei Valehtele",
    "partners.comparison.subheadline": "Katso tarkalleen paljon enemmän pidät Bargnilla vs perinteiset alustat. Spoileri: Se on paljon.",
    "partners.comparison.transactionValue": "Transaktion Arvo",
    "partners.comparison.transactionHelper": "Säädä nähdäksesi potentiaalisi ansiot",
    "partners.comparison.platformCommission": "Alustan Provisio",
    "partners.comparison.commissionHelper": "Tyypillinen range: 25-45%",
    "partners.comparison.traditional.title": "Perinteiset Alustat",
    "partners.comparison.traditional.subtitle": "UberEats, Wolt, jne.",
    "partners.comparison.bargn.title": "Bargn",
    "partners.comparison.bargn.subtitle": "Nolla Provisiota, Maksimi Profit",
    "partners.comparison.originalPrice": "Alkuperäinen Hinta",
    "partners.comparison.customerPays": "Asiakas Maksaa",
    "partners.comparison.off": "alennus",
    "partners.comparison.revenue": "Sun Tulot",
    "partners.comparison.platformTakes": "Alusta Ottaa",
    "partners.comparison.bargnTakes": "Bargn Ottaa",
    "partners.comparison.youKeep": "Sä Pidät",
    "partners.comparison.margin": "voittomarginaali",
    "partners.comparison.difference.title": "Sun Etu Bargnilla",
    "partners.comparison.difference.extraRevenue": "Extra Tulot Per Transaktio",
    "partners.comparison.difference.moreProfit": "Enemmän Voittoo",
    "partners.comparison.difference.description": "Per transaktio. Kerro tää sadoilla asiakkailla kuukaudessa.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
