import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "fi" | "sv";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    members: "Members",
    partners: "Partners",
    howItWorks: "How It Works",
    about: "About",
    blog: "Blog",
    campaign: "Campaign",
    letsGo: "Let's Go",
    updateBanner: "Website is under update",
    heroHeadline: "50% Off Everything",
    heroSubhead: "AI-powered discounts that actually work",
    heroText: "Join thousands who've cracked the code to smart spending. Our AI learns your preferences and serves up personalized 50% discounts at local hotspots.",
    heroDiscountRate: "Discount Rate",
    heroPartners: "Partners",
    heroSaved: "Saved",
    partnerUp: "Partner Up (We're Cool Like That)",
    // Members page
    membersHero: "Join 10K+ Legends Who Never Pay Sucker Prices",
    membersHeroSub: "",
    membersHeroDesc: "Welcome to the club where paying full price is basically illegal. Our AI is literally smarter than your ex and finds you deals that'll make your wallet do a happy dance.",
    startSaving: "Start Saving Now",
    becomePartner: "Become a Partner",
    happyMembers: "Happy Members",
    avgSavings: "Average Savings",
    avgAnnualSavings: "Avg Annual Savings",
    partnerOutlets: "Partner Outlets",
    whyLoveUs: "Why You'll Love Us",
    perksThatSlap: "Perks That Actually Slap",
    perksDesc: "We're not just another discount app - we're your financial wingman with benefits that pay for themselves faster than you can say 'broke no more'.",
    unlimitedDiscounts: "Unlimited 'Hell Yeah' Discounts",
    unlimitedDiscountsDesc: "500+ spots where you flex that 50% savings like the financial genius you are",
    aiNotDumb: "AI That's Not Dumb",
    aiNotDumbDesc: "Unlike other apps, our AI actually reads the room and serves recommendations that don't suck",
    vipTreatment: "VIP Treatment (For Real)",
    vipTreatmentDesc: "Cut the line, skip the peasants, get first access to the good stuff before it's cool",
    supportDamn: "Support That Gives a Damn",
    supportDamnDesc: "Real humans who actually solve problems instead of copy-pasting 'have you tried turning it off'",
    pricingTitle: "Pricing That Won't Rob You",
    pricingDesc: "Two options: save money monthly or save even more money yearly. Either way, you're winning at life.",
    monthlyFlex: "Monthly Flex",
    annualPower: "Annual Power Move",
    bestValue: "Best Value",
    perMonth: "/month",
    perYear: "/year",
    saveAnnually: "Save €52.6 annually",
    joinNow: "Join Now",
    cancelAnytime: "Cancel anytime",
    monthsFree: "2 months FREE bonus",
    bothPlans: "Both plans include:",
    bothPlansDesc: "All premium features, unlimited discounts, AI recommendations, priority support, and access to exclusive partners.",
    noHiddenFees: "No hidden fees • Cancel anytime • 30-day money-back guarantee",
    memberStories: "Member Stories",
    realMembers: "Real Members, Real Savings",
    realMembersDesc: "See how our community is saving thousands while living their best life.",
    exclusiveFeatures: "Exclusive Features",
    membersOnlyPerks: "Members-Only Perks",
    membersOnlyPerksDesc: "Access features that regular users can only dream about.",
    earlyAccess: "Early Access to New Partners",
    earlyAccessDesc: "Be the first to discover new restaurants, shops, and services before they're available to the public",
    exclusiveEvents: "Exclusive Member Events",
    exclusiveEventsDesc: "VIP events, networking opportunities, and special experiences designed just for our community",
    limitedOffers: "Limited-Time Member Offers",
    limitedOffersDesc: "Flash sales, bonus discounts, and seasonal promotions exclusive to members",
    faqTitle: "FAQ",
    faqHeading: "Got Questions? We Got Answers",
    faqQ1: "Can I bail if I want?",
    faqA1: "Duh! Cancel whenever you want, no guilt trips or weird exit surveys. We're not your clingy ex.",
    faqQ2: "How does this magic work?",
    faqA2: "Flash that Bargn membership like the VIP you are. Boom - 50% off instantly. No coupons, no hassle, no cap.",
    faqQ3: "Am I trapped in a contract?",
    faqA3: "Hell no! We're not a gym membership. Month-to-month or yearly - your choice. Cancel whenever, we'll still be friends.",
    ctaHeading: "Ready to Graduate From Broke?",
    ctaDesc: "Join the club where paying full price is for beginners. Your future self (and bank account) will literally thank you.",
    // About page
    "about.hero.badge": "MEET THE REBELS",
    "about.hero.headline1": "We're Not Your",
    "about.hero.headline2": "Average",
    "about.hero.headline3": "Discount App",
    "about.hero.subtext": "We're the rebels who said 'nah' to paying full price and built an AI that actually gets you. No cap, we're literally changing how people save money.",
    "about.hero.cta1": "Let's Go",
    "about.hero.cta2": "Join The Squad",
    "about.story.badge": "Our Story",
    "about.story.headline": "Started From The Bottom, Now We're... Still Broke But With Better Deals",
    "about.story.text": "Founded in 2023 by a group of Gen Z entrepreneurs who were tired of being financially drained by overpriced everything. We looked at the discount space and thought 'this is giving boomer energy' - so we decided to fix it with AI that doesn't suck.",
    "about.story.founded": "Founded 2023",
    "about.story.tagline": "Disrupting Discounts",
    "about.mission.badge": "Our Mission",
    "about.mission.headline": "Making Full Price Extinct",
    "about.mission.text": "Our mission is simple: use AI to connect people with 50% discounts on everything they actually want. No more random coupons for stuff you'll never use. We're creating a world where paying full price feels illegal.",
    "about.mission.card1.title": "50%",
    "about.mission.card1.desc": "Average Discount on Every Purchase",
    "about.mission.card2.title": "AI-Powered",
    "about.mission.card2.desc": "Personalized Recommendations That Actually Work",
    "about.mission.card3.title": "Zero Fees",
    "about.mission.card3.desc": "No Hidden Charges, Just Pure Savings",
    "about.values.badge": "Our Values",
    "about.values.headline": "What We Stand For",
    "about.values.subtext": "These aren't just words on a wall. They're the principles we live by every single day.",
    "about.values.card1.title": "Innovation That Slaps",
    "about.values.card1.desc": "We use cutting-edge AI because why settle for basic algorithms when you can have ones that understand your vibe?",
    "about.values.card2.title": "No Cap Policy",
    "about.values.card2.desc": "We're transparent about everything - fees, partnerships, how our AI works. No hidden agenda, just straight facts.",
    "about.values.card3.title": "Community First",
    "about.values.card3.desc": "Our users aren't customers, they're family. We build for the community, not just the algorithm.",
    "about.team.badge": "Meet The Squad",
    "about.team.headline": "The Humans Behind The Magic",
    "about.team.subtext": "We're a diverse team of innovators, dreamers, and deal-hunters who believe technology should make life better, not more complicated.",
    "about.team.member1.name": "Alex Chen",
    "about.team.member1.role": "Founder & CEO",
    "about.team.member1.bio": "The visionary who said 'enough' to full prices",
    "about.team.member2.name": "Sarah Kim",
    "about.team.member2.role": "Chief Technology Officer",
    "about.team.member2.bio": "Codes magic and makes servers dance",
    "about.team.member3.name": "Marcus Johnson",
    "about.team.member3.role": "AI Engineering Lead",
    "about.team.member3.bio": "Teaches AI to understand your vibe",
    "about.team.member4.name": "Emma Rodriguez",
    "about.team.member4.role": "Head of Growth",
    "about.team.member4.bio": "Spreads the word about saving money",
    "about.team.cta": "Join Our Team",
    "about.cta.headline": "Ready to Join the Revolution?",
    "about.cta.subtext": "Become part of a movement that's changing how people save money. No cap, just results.",
    "about.cta.button1": "Let's Go",
    "about.cta.button2": "Join The Squad",
    // How It Works page
    "how.badge": "STEP-BY-STEP GUIDE",
    "how.hero.headline": "Save 50% Without Selling Your Soul",
    "how.hero.description": "Look, we get it. You're broke but bougie. We've made saving money so stupidly simple, even your tech-challenged aunt could figure it out. No PhD in couponing required.",
    "how.timeline.label": "Idiot-Proof Guide",
    "how.timeline.heading": "Your Journey from Broke to Woke",
    "how.timeline.subheading": "Follow these 5 braindead-simple steps and start flexing those savings. Seriously, if you mess this up, we can't help you.",
    "how.step1.title": "Download & Don't Cry",
    "how.step1.description": "Download our app faster than you swipe left on dating apps. Pick a plan, pay up, and boom – you're officially part of the savings mafia.",
    "how.step1.bullet1": "Download from App Store or Google Play",
    "how.step1.bullet2": "Choose monthly or yearly plan",
    "how.step2.title": "Stalk Our Partners (Legally)",
    "how.step2.description": "Use our creepy-good AI map to find 500+ places near you that actually want to give you money off. It's like Tinder, but for your wallet.",
    "how.step2.bullet1": "Browse 500+ partner locations",
    "how.step2.bullet2": "Filter by category and distance",
    "how.step3.title": "Swipe Right on Savings",
    "how.step3.description": "Browse deals like you browse memes – mindlessly but with purpose. Swipe to activate that sweet 50% off. Our AI stalks your preferences (in a good way).",
    "how.step3.bullet1": "Swipe to activate instant deals",
    "how.step3.bullet2": "AI learns your preferences",
    "how.step4.title": "Flash That Digital Bling",
    "how.step4.description": "Show your phone to the staff like you're some VIP hotshot. They'll verify you're legit and not some discount fraud artist.",
    "how.step4.bullet1": "Show activated deal to staff",
    "how.step4.bullet2": "Instant verification & approval",
    "how.step5.title": "Pay Half, Feel Whole",
    "how.step5.description": "Hand over 50% of what you normally would and walk away like the financial genius you are. Rate the experience so our AI gets even creepier at knowing what you want.",
    "how.step5.bullet1": "Pay only 50% of original price",
    "how.step5.bullet2": "Rate experience for better AI",
    "how.why.label": "Why We're Not Idiots",
    "how.why.heading": "Designed by Lazy People, for Lazy People",
    "how.why.description": "We hate complicated stuff as much as you do. So we made this so simple, it's basically insulting to your intelligence.",
    "how.benefit1.title": "Zero Brain Cells Required",
    "how.benefit1.description": "No scissors for coupons, no memory palace for codes, no calendar alerts for expiry dates. Just instant gratification for your shopping addiction.",
    "how.benefit2.title": "Faster Than Your Ex's Rebound",
    "how.benefit2.description": "Activate discounts quicker than you can say 'financial responsibility.' No waiting around like you're at the DMV.",
    "how.benefit3.title": "AI That Actually Gets You",
    "how.benefit3.description": "Our AI learns your taste better than your therapist learns your trauma. It'll suggest deals you actually want, not random junk.",
    // Partners page
    "partners.hero.badge": "BUSINESS PARTNERSHIP",
    "partners.hero.headline1": "500+ Businesses Can't Be Wrong",
    "partners.hero.headline2": "(But Your Competition Might Be)",
    "partners.hero.subheadline": "",
    "partners.hero.body": "Look, while your competitors are still paying hefty commissions... our partners are laughing all the way to the bank.",
    "partners.hero.cta.primary": "Apply Now",
    "partners.hero.cta.secondary": "Join as Member",
    "partners.stats.activePartners": "Active Partners",
    "partners.stats.commissionFees": "Commission Fees",
    "partners.stats.avgIncrease": "Avg Customer Increase",
    "partners.stats.qualityMembers": "Quality Members",
    "partners.signup.badge": "Quick Start",
    "partners.signup.headline": "Sign Up Now - No Applications!",
    "partners.signup.subheadline": "Create your business account instantly and start onboarding immediately. No waiting, no lengthy approval process.",
    "partners.signup.steps.step1.title": "Create Account",
    "partners.signup.steps.step1.description": "Sign up instantly with your business email and basic info",
    "partners.signup.steps.step1.duration": "Takes 2 minutes",
    "partners.signup.steps.step2.title": "Set Your 50% Offers",
    "partners.signup.steps.step2.description": "Choose which services get 50% discount (3x per year per customer)",
    "partners.signup.steps.step2.action": "Define your offers",
    "partners.signup.steps.step3.title": "Go Live",
    "partners.signup.steps.step3.description": "Add photos, menu, logo. Quick verification, then live!",
    "partners.signup.steps.step3.action": "Start receiving customers",
    "partners.signup.form.venueName": "Venue Name",
    "partners.signup.form.venueNamePlaceholder": "Your business name",
    "partners.signup.form.city": "City",
    "partners.signup.form.cityPlaceholder": "Where are you located?",
    "partners.signup.form.email": "Email",
    "partners.signup.form.emailPlaceholder": "Business email address",
    "partners.signup.form.button": "Apply Now",
    "partners.signup.form.validation": "Please fill in all fields",
    "partners.signup.form.success": "Application submitted! We'll be in touch soon.",
    "partners.signup.benefits.noApplication": "No Application Required",
    "partners.signup.benefits.instantSetup": "Instant Setup",
    "partners.signup.benefits.zeroCommission": "Zero Commission",
    "partners.comparison.badge": "The Math",
    "partners.comparison.headline": "The Numbers Don't Lie",
    "partners.comparison.subheadline": "See exactly how much more you keep with Bargn vs traditional platforms. Spoiler: It's a lot.",
    "partners.comparison.transactionValue": "Transaction Value",
    "partners.comparison.transactionHelper": "Adjust to see your potential earnings",
    "partners.comparison.platformCommission": "Platform Commission",
    "partners.comparison.commissionHelper": "Typical range: 25-45%",
    "partners.comparison.traditional.title": "Traditional Platforms",
    "partners.comparison.traditional.subtitle": "UberEats, Wolt, etc.",
    "partners.comparison.bargn.title": "Bargn",
    "partners.comparison.bargn.subtitle": "Zero Commission, Maximum Profit",
    "partners.comparison.originalPrice": "Original Price",
    "partners.comparison.customerPays": "Customer Pays",
    "partners.comparison.off": "off",
    "partners.comparison.revenue": "Your Revenue",
    "partners.comparison.platformTakes": "Platform Takes",
    "partners.comparison.bargnTakes": "Bargn Takes",
    "partners.comparison.youKeep": "You Keep",
    "partners.comparison.margin": "profit margin",
    "partners.comparison.difference.title": "Your Advantage with Bargn",
    "partners.comparison.difference.extraRevenue": "Extra Revenue Per Transaction",
    "partners.comparison.difference.moreProfit": "More Profit",
    "partners.comparison.difference.description": "Per transaction. Multiply this by hundreds of customers per month.",
    // Campaign page
    "campaign.hero.badge": "🔥 40% REVENUE SHARE ✨",
    "campaign.hero.headline": "Make Bank While You Create",
    "campaign.hero.subheadline": "40% Revenue Share • No BS • Actual Money",
    "campaign.hero.description": "Tired of getting paid in 'exposure'? We're literally throwing money at creators who can make our discount app go viral. No follower minimums, no soul-crushing contracts, just cold hard cash for quality content. Finland's never seen anything this spicy.",
    "campaign.hero.cta1": "Start My Revenue Stream",
    "campaign.hero.cta2": "Learn How We Pay",
    "campaign.stats.revenueShare": "Revenue Share",
    "campaign.stats.activeCreators": "Active Creators",
    "campaign.stats.paidOut": "Paid Out",
    "campaign.stats.minPayout": "Min Payout",
    "campaign.goldRush.title": "The Bargn Influencer Gold Rush",
    "campaign.goldRush.description": "Plot twist: we actually pay our creators. While other companies offer you 'brand partnerships' worth three energy drinks and a sad emoji, we're out here sharing real revenue. Every person who signs up using your content? You get 40% of their subscription fees. Forever. Yeah, we said forever.",
    "campaign.goldRush.benefit1.title": "Actual Revenue Share (Not Monopoly Money)",
    "campaign.goldRush.benefit1.description": "40% of every subscription from your referrals goes straight to your bank account. No minimum thresholds, no 'we'll pay you when Jupiter aligns with Mars' nonsense. Just real money for real work.",
    "campaign.goldRush.benefit2.title": "Creative Control That Actually Means Something",
    "campaign.goldRush.benefit2.description": "Make content that fits your vibe. We're not gonna micromanage your creativity or make you say cringe corporate buzzwords. Your audience trusts you, not our marketing department.",
    "campaign.goldRush.benefit3.title": "Exclusive Access (Because You're Special)",
    "campaign.goldRush.benefit3.description": "First dibs on new features, direct line to our team, and insider info on upcoming campaigns. Plus, your own personal dashboard to track earnings in real-time. Transparency is sexy.",
    "campaign.moneyTalk.title": "The Money Talk (Our Favorite Subject)",
    "campaign.moneyTalk.subtitle": "Let's be real - you're here for the cash. Here's the tea:",
    "campaign.moneyTalk.card1.title": "Up to 40% Revenue Share",
    "campaign.moneyTalk.card1.description": "€8.8 monthly sub = €3.52 for you per referral. €53 yearly sub = €21.20 for you. Math that actually makes sense.",
    "campaign.moneyTalk.card2.title": "No Minimum Payout BS",
    "campaign.moneyTalk.card2.description": "Some platforms make you wait until you hit €100 to get paid. We pay out from €5. Because rent doesn't wait for arbitrary thresholds.",
    "campaign.moneyTalk.card3.title": "Fast Payouts (Like, Actually Fast)",
    "campaign.moneyTalk.card3.description": "Weekly payouts straight to your bank. No 'the check is in the mail' vibes. We're not your sketchy ex who owes you money.",
    // 404 Page
    "404.headline": "Wrong Turn, Right App",
    "404.subtext": "Page missing, deals not. Let's get you back to the gold rush.",
    "404.cta": "Back to Home",
    // Privacy Policy
    "privacy.intro": "The lawyers made us write this. Grab a coffee, it's dry.",
    "privacy.title": "Privacy Policy",
    // Terms of Service
    "terms.intro": "Yes, you have to read this. No, we don't like it either.",
    "terms.title": "Terms of Service",
    // Cookie Policy
    "cookies.intro": "Not the chocolate chip kind. The internet stalker kind.",
    "cookies.title": "Cookie Policy",
    // Cookie Consent Banner
    "cookieConsent.title": "We Gotta Talk About Cookies (The Boring Kind)",
    "cookieConsent.description": "Look, we're legally required to tell you we use cookies. But unlike your ex, these cookies actually serve a purpose - making your experience less terrible. You can vibe with all of them or just the essentials. Your call.",
    "cookieConsent.moreInfo": "Want the full legal tea?",
    "cookieConsent.learnMore": "Read our Cookie Policy",
    "cookieConsent.acceptAll": "Accept All (We're Cool)",
    "cookieConsent.rejectAll": "Only Essentials (Picky)",
    "cookieConsent.customize": "Let Me Choose",
    "cookieConsent.settingsTitle": "Cookie Settings (For The Control Freaks)",
    "cookieConsent.essential.title": "Essential Cookies (Can't Say No)",
    "cookieConsent.essential.description": "These keep the lights on. Without them, the app literally doesn't work. Sorry not sorry, you're stuck with these.",
    "cookieConsent.analytics.title": "Analytics Cookies (We're Nosy)",
    "cookieConsent.analytics.description": "Help us see what's working and what's trash. No personal data sold, we promise. We just wanna know if people actually use that button.",
    "cookieConsent.marketing.title": "Marketing Cookies (The Stalker Ones)",
    "cookieConsent.marketing.description": "These follow you around the internet like your high school crush. They show you ads that might actually be relevant instead of random garbage.",
    "cookieConsent.savePreferences": "Save My Choices",
    "cookieConsent.back": "Back",
    "campaign.contentIdeas.title": "Content Ideas That Don't Make You Cringe",
    "campaign.contentIdeas.subtitle": "Here's some inspo that won't make your followers unfollow you:",
    "campaign.contentIdeas.idea1.title": "'I Tried the Discount App Everyone's Talking About'",
    "campaign.contentIdeas.idea1.description": "Show your genuine reaction to finding 50% discounts at your favorite spots. Spoiler alert: you're gonna be shook.",
    "campaign.contentIdeas.idea2.title": "'How I Save €500/Month Without Being Cheap'",
    "campaign.contentIdeas.idea2.description": "Share your actual savings and flex on people still paying full price like it's 2019. Educational and slightly savage.",
    "campaign.contentIdeas.idea3.title": "'Testing If This Discount App Is Actually Legit'",
    "campaign.contentIdeas.idea3.description": "Document your first month using Bargn. Spoiler: it is legit, and your audience will want in on the savings.",
    "campaign.testimonials.title": "What Our Creator Fam Says",
    "campaign.testimonials.testimonial1.name": "Aino L., Lifestyle Creator (180k followers)",
    "campaign.testimonials.testimonial1.quote": "I made €2,400 in my first three months just from sharing something I actually use daily. The revenue share is no joke - they actually pay what they promise. Best partnership I've ever had.",
    "campaign.testimonials.testimonial2.name": "Ville K., Tech Reviewer (95k followers)",
    "campaign.testimonials.testimonial2.quote": "Finally, a brand that doesn't treat creators like free advertising space. The 40% revenue share means I can focus on quality content instead of hustling for multiple tiny sponsorships. Game changer.",
    "campaign.requirements.title": "What We Actually Need From You",
    "campaign.requirements.subtitle": "No impossible standards, just real talk about what makes this work:",
    "campaign.requirements.req1": "Any social media presence (yes, even 500 followers counts)",
    "campaign.requirements.req2": "Authentic content that doesn't scream 'obvious ad'",
    "campaign.requirements.req3": "Based in Finland (sorry, we don't make the geography rules)",
    "campaign.requirements.req4": "Can legally enter contracts (aka you're 18+ and not a cat)",
    "campaign.process.title": "How to Join the Money Club",
    "campaign.process.subtitle": "Four steps between you and getting paid for your creativity:",
    "campaign.process.step1.title": "Apply",
    "campaign.process.step1.description": "Fill out our form (it's shorter than your last Instagram caption)",
    "campaign.process.step2.title": "Chat",
    "campaign.process.step2.description": "Quick video call to make sure we're a good fit (we probably are)",
    "campaign.process.step3.title": "Create",
    "campaign.process.step3.description": "Make content about Bargn in your style, your way",
    "campaign.process.step4.title": "Get Paid",
    "campaign.process.step4.description": "Watch your bank account grow every time someone signs up",
    "campaign.faq.title": "Questions? We Got Receipts",
    "campaign.faq.subtitle": "(And they're probably more honest than you expected)",
    "campaign.faq.q1": "Is this revenue share thing actually real or just marketing BS?",
    "campaign.faq.a1": "It's real AF. We literally give you 40% of every subscription from your referrals. We've already paid out over €50k to creators. Want receipts? Our top creator made €4.2k last month. Math don't lie.",
    "campaign.cta.title": "Ready to Make Some Actual Money?",
    "campaign.cta.description": "Join 200+ creators who've figured out that getting paid fairly is way better than working for 'exposure'",
    "campaign.cta.button": "Start My Revenue Stream",
    // Blog page
    "blog.hero.badge": "BARGN BLOG",
    "blog.hero.headline": "Stories That Matter",
    "blog.hero.subheadline": "From Our Community",
    "blog.featured.tag": "Must Read",
    "blog.featured.title": "10 Genius Ways to Maximize Your 50% Discounts",
    "blog.featured.meta": "8 min read",
    "blog.categories.all": "All Posts",
    "blog.categories.guides": "Discount Guides",
    "blog.categories.spotlights": "Partner Spotlights",
    "blog.categories.stories": "Success Stories",
    "blog.article1.title": "How Sarah Saved €5,000 in 6 Months Using Bargn",
    "blog.article1.excerpt": "Real member, real savings, real receipts. Sarah went from broke to financially savvy.",
    "blog.article1.category": "Success Stories",
    "blog.article2.title": "Why Traditional Coupon Apps Are Scamming You",
    "blog.article2.excerpt": "Hot take: Those 'deal' apps make money off you while you think you're saving.",
    "blog.article2.category": "Discount Guides",
    "blog.article3.title": "50 New Partners Just Joined – Here's Where",
    "blog.article3.excerpt": "We're expanding faster than ever. Check out the new spots where you can save.",
    "blog.article3.category": "Partner Spotlights",
    // Footer
    "footer.newsletter.title": "Newsletter (No Spam, Just Vibes)",
    "footer.newsletter.placeholder": "your@email.com",
    "footer.newsletter.button": "Subscribe",
    "footer.links.privacy": "Privacy Policy",
    "footer.links.terms": "Terms of Service",
    "footer.links.cookies": "Cookie Policy",
    "footer.info.address": "Helsinki, Finland",
    "footer.info.businessId": "Y-tunnus: 1234567-8",
    "footer.copyright": "© 2024 Bargn. All rights reserved.",
    "footer.tagline": "Discover. Save. Repeat.",
    "chatWidget": "Ask Bargn AI",
  },
  fi: {
    home: "Koti",
    members: "Jäsenet",
    partners: "Kumppanit",
    howItWorks: "Miten Se Toimii",
    about: "Tietoa",
    blog: "Blogi",
    campaign: "Kampanja",
    letsGo: "Aloitetaan",
    updateBanner: "Verkkosivusto päivitetään",
    heroHeadline: "50% Alennus Kaikesta",
    heroSubhead: "AI-vetoisia alennuksia jotka oikeesti toimii",
    heroText: "Liity tuhansien joukkoon jotka on crackannu koodin fiksun kuluttamisen. Meidän AI oppii sun mieltymykset ja tarjoilee personoituja 50% alennuksia paikallisista hoteista.",
    heroDiscountRate: "Alennusprosentti",
    heroPartners: "Kumppania",
    heroSaved: "Säästetty",
    partnerUp: "Kumppani (Ollaan Cooli Sillä Tavalla)",
    // Members page
    membersHero: "Liity 10K+ Legendaan Jotka Ei Ikinä Maksa Mulkku Hintoja",
    membersHeroSub: "",
    membersHeroDesc: "Tervetuloa klubiin missä täyden hinnan maksaminen on periaatteessa laitonta. Meidän AI on kirjaimellisesti fiksumpi ku sun ex ja löytää sulle diilejä jotka saa sun lompakon tanssimaan ilosta.",
    startSaving: "Aloita Säästäminen",
    becomePartner: "Ryhdy Kumppaniksi",
    happyMembers: "Tyytyväistä Jäsentä",
    avgSavings: "Keskisäästöt",
    avgAnnualSavings: "Keskim. Vuosisäästöt",
    partnerOutlets: "Kumppanipaikkoja",
    whyLoveUs: "Miksi Rakastut Meihin",
    perksThatSlap: "Edut Jotka Oikeesti Slappaa",
    perksDesc: "Me ei olla vaan joku random alennusappi - me ollaan sun taloudellinen wingman eduilla jotka maksaa ittensä takasin nopeemmin ku ehdit sanoo 'oon rikki'.",
    unlimitedDiscounts: "Rajattomat 'Vittu Joo' Alennukset",
    unlimitedDiscountsDesc: "500+ paikkaa missä flexaat sitä 50% säästöö niinku se taloudellinen nero mitä oot",
    aiNotDumb: "AI Joka Ei Oo Tyhmä",
    aiNotDumbDesc: "Toisin ku muut apit, meidän AI oikeesti lukee tilanteen ja tarjoilee suosituksia jotka ei imu",
    vipTreatment: "VIP Kohtelu (Oikeesti)",
    vipTreatmentDesc: "Ohita jono, skipppaa köyhät, saat ensipääsyn parhaaseen kamaan ennenku se on coolia",
    supportDamn: "Tuki Joka Välittää",
    supportDamnDesc: "Oikeita ihmisiä jotka oikeesti ratkoo ongelmia sen sijaan et copypasteis 'ootko koittanu sammuttaa sen'",
    pricingTitle: "Hinnoittelu Joka Ei Ryöstä Sua",
    pricingDesc: "Kaks vaihtoehtoo: säästä rahaa kuukausittain tai säästä vielä enemmän vuosittain. Kumminki voitat elämässä.",
    monthlyFlex: "Kuukausittainen Flexaus",
    annualPower: "Vuosittainen Power Move",
    bestValue: "Paras Tarjous",
    perMonth: "/kk",
    perYear: "/vuosi",
    saveAnnually: "Säästä €52.6 vuodessa",
    joinNow: "Liity Nyt",
    cancelAnytime: "Peruuta koska vaan",
    monthsFree: "2 kuukautta ILMAISEKS bonuksena",
    bothPlans: "Molemmat suunnitelmat sisältää:",
    bothPlansDesc: "Kaikki premium ominaisuudet, rajattomat alennukset, AI suositukset, priority tuki, ja pääsy eksklusiivisiin kumppaneihin.",
    noHiddenFees: "Ei piilomaksuja • Peruuta koska vaan • 30 päivän rahat takas -takuu",
    memberStories: "Jäsentarinoita",
    realMembers: "Oikeita Jäseniä, Oikeita Säästöjä",
    realMembersDesc: "Katso miten meidän yhteisö säästää tuhansia samalla ku elää parasta elämäänsä.",
    exclusiveFeatures: "Eksklusiiviset Ominaisuudet",
    membersOnlyPerks: "Vain Jäsenille -Edut",
    membersOnlyPerksDesc: "Pääsy ominaisuuksiin joista tavalliset käyttäjät voi vaan unelmoida.",
    earlyAccess: "Ennakko-oikeus Uusiin Kumppaneihin",
    earlyAccessDesc: "Ole eka joka löytää uudet ravintolat, kaupat ja palvelut ennenku ne on julkisesti saatavilla",
    exclusiveEvents: "Eksklusiiviset Jäsentapahtumat",
    exclusiveEventsDesc: "VIP tapahtumat, verkostoitumismahdollisuudet ja erikoiskokemuksia suunniteltu vaan meidän yhteisölle",
    limitedOffers: "Rajoitetun Ajan Jäsentarjoukset",
    limitedOffersDesc: "Flash myynti, bonusalennukset ja kausi-kampanjat vaan jäsenille",
    faqTitle: "UKK",
    faqHeading: "Sul On Kysymyksiä? Meil On Vastauksia",
    faqQ1: "Voinks bailaa jos haluan?",
    faqA1: "Duh! Peruuta koska vaan, ei syyllisyysrippei tai outoja exit kyselyjä. Me ei olla sun tahmee ex.",
    faqQ2: "Miten tää taika toimii?",
    faqA2: "Flashaa toi Bargn jäsenyys niinku se VIP mitä oot. Boom - 50% alennust heti. Ei kuponkeja, ei häslingii, ei cap.",
    faqQ3: "Olenko loukkus sopimuksessa?",
    faqA3: "Helvetti ei! Me ei olla kuntosalijäsenyys. Kuukausittain tai vuosittain - sun valinta. Peruuta milloin vaan, ollaan silti kavereita.",
    ctaHeading: "Valmiina Valmistumaan Köyhyydestä?",
    ctaDesc: "Liity klubiin missä täyden hinnan maksaminen on aloittelijoille. Sun tuleva minä (ja pankkitili) kiittää sua kirjaimellisesti.",
    // About page
    "about.hero.badge": "MEET THE REBELS",
    "about.hero.headline1": "Me Ei Olla Sun",
    "about.hero.headline2": "Tavallinen",
    "about.hero.headline3": "Alennussovellus",
    "about.hero.subtext": "Me ollaan ne kapinalliset jotka sanoi 'nah' täyden hinnan maksulle ja rakensettiin AI joka oikeesti ymmärtää sut. No cap, me muutetaan literally miten ihmiset säästää rahaa.",
    "about.hero.cta1": "Aloitetaan",
    "about.hero.cta2": "Liity Tiimiin",
    "about.story.badge": "Meidän Tarina",
    "about.story.headline": "Alotettiin Pohjalta, Nyt Ollaan... Vielä Köyhiä Mut Paremmilla Diileillä",
    "about.story.text": "Perustettu 2023 Gen Z yrittäjien porukalla jotka oli väsyneitä siihen et joka ikinen asia on liian kallista. Me katsottiin alennusbisnestä ja ajateltiin 'tää on boomeri energiaa' - ni me päätettiin korjata se AI:lla joka ei ime.",
    "about.story.founded": "Perustettu 2023",
    "about.story.tagline": "Disruptoidaan Alennukset",
    "about.mission.badge": "Meidän Missio",
    "about.mission.headline": "Tehdään Täydestä Hinnasta Sukupuuttoon Kuollut",
    "about.mission.text": "Meidän missio on yksinkertanen: käytetään AI:ta yhdistääksemme ihmisiä 50% alennuksiin kaikesta mitä ne oikeesti haluu. Ei enää randomeja kuponkeja tavaralle mitä et ikinä käytä. Me luodaan maailma missä täyden hinnan maksaminen tuntuu laittomalta.",
    "about.mission.card1.title": "50%",
    "about.mission.card1.desc": "Keskialennust Jokaisesta Ostoksesta",
    "about.mission.card2.title": "AI-Käyttöinen",
    "about.mission.card2.desc": "Personoituja Suosituksia Jotka Oikeesti Toimii",
    "about.mission.card3.title": "Nolla Maksuja",
    "about.mission.card3.desc": "Ei Piilomaksuja, Vaan Puhasta Säästöö",
    "about.values.badge": "Meidän Arvot",
    "about.values.headline": "Mitä Me Edustetaan",
    "about.values.subtext": "Nää ei oo vaan sanoja seinällä. Nää on periaatteita joita me eletään joka ikinen päivä.",
    "about.values.card1.title": "Innovaatio Joka Läjää",
    "about.values.card1.desc": "Me käytetään huippuluokan AI:ta koska miks tyytys perus algoritmeihin ku voit saada sellasia jotka ymmärtää sun viben?",
    "about.values.card2.title": "No Cap Politiikka",
    "about.values.card2.desc": "Ollaan läpinäkyviä kaikesta - maksut, kumppanuudet, miten meidän AI toimii. Ei piiloteltua agendaa, vaan suoria faktoja.",
    "about.values.card3.title": "Yhteisö Ekana",
    "about.values.card3.desc": "Meidän käyttäjät ei oo asiakkaita, ne on perhettä. Me rakennetaan yhteisölle, ei pelkälle algoritmille.",
    "about.team.badge": "Meet The Squad",
    "about.team.headline": "Ihmiset Magian Takana",
    "about.team.subtext": "Me ollaan monipuolinen tiimi innovoijia, unelmoijia ja diilimetsästäjiä jotka uskoo et teknologian pitäis tehä elämästä parempaa, ei monimutkasempaa.",
    "about.team.member1.name": "Alex Chen",
    "about.team.member1.role": "Perustaja & CEO",
    "about.team.member1.bio": "Visionääri joka sano 'tarpeeks' täysille hinnoille",
    "about.team.member2.name": "Sarah Kim",
    "about.team.member2.role": "Teknologiajohtaja",
    "about.team.member2.bio": "Koodaa taikuutta ja saa palvelimet tanssimaan",
    "about.team.member3.name": "Marcus Johnson",
    "about.team.member3.role": "AI-Insinöörijohtaja",
    "about.team.member3.bio": "Opettaa AI:ta ymmärtämään sun viben",
    "about.team.member4.name": "Emma Rodriguez",
    "about.team.member4.role": "Kasvujohtaja",
    "about.team.member4.bio": "Levittää sanaa rahojen säästämisestä",
    "about.team.cta": "Liity Tiimiin",
    "about.cta.headline": "Valmiina Liittymään Vallankumoukseen?",
    "about.cta.subtext": "Tuu osaksi liikettä joka muuttaa miten ihmiset säästää rahaa. Ei cap, vaan tuloksia.",
    "about.cta.button1": "Aloitetaan",
    "about.cta.button2": "Liity Tiimiin",
    // How It Works page
    "how.badge": "VAIHE VAIHEELTA OPAS",
    "how.hero.headline": "Säästä 50% Ilman Sielun Myymistä",
    "how.hero.description": "Katso, me snapataan. Oot köyhä mut bougie. Me tehty rahojen säästämisestä niin typerän yksinkertaista, et jopa sun tekniikka-haastava täti vois oppia sen. Ei PhD kuponkeiluun vaadita.",
    "how.timeline.label": "Idiootti-Varma Opas",
    "how.timeline.heading": "Sun Matka Köyhästä Rikkaaks",
    "how.timeline.subheading": "Seuraa näitä 5 aivo-kuollutta askeletta ja ala flexaa noita säästöjä. Oikeesti, jos mokat tän, me ei voida auttaa sua.",
    "how.step1.title": "Lataa & Älä Itke",
    "how.step1.description": "Lataa appi nopeemmin ku swippaat vasemmalle treffiapeissa. Valitse suunnitelma, maksa, ja boom - oot virallisesti osa säästömaffiaa.",
    "how.step1.bullet1": "Lataa App Storesta tai Google Playsta",
    "how.step1.bullet2": "Valitse kuukausi- tai vuosisuunnitelma",
    "how.step2.title": "Stalkaa Kumppaneita (Laillisesti)",
    "how.step2.description": "Käytä meidän creepy-hyvää AI karttaa löytääksesi 500+ paikkaa lähellä sua jotka oikeesti haluu antaa sulle rahaa pois. Se on niinku Tinder, mut sun lompakolle.",
    "how.step2.bullet1": "Selaa 500+ kumppanipaikkaa",
    "how.step2.bullet2": "Filtteröi kategorian ja etäisyyden mukaan",
    "how.step3.title": "Swaippaa Oikealle Säästöjen Kanssa",
    "how.step3.description": "Selaa diilejä niinku selaat meemejä - ajattelemattomasti mut tarkoituksella. Swaippaa aktivoidaksesi sen swagin 50% alennuksen. Meidän AI stalkkaa sun mieltymyksiä (hyvällä tavalla).",
    "how.step3.bullet1": "Swaippaa aktivoidaksesi instant diilit",
    "how.step3.bullet2": "AI oppii sun mieltymykset",
    "how.step4.title": "Väläytä Sitä Digitaalista Blingiä",
    "how.step4.description": "Näytä puhelin henkilökunnalle niinku oisit joku VIP hotshot. Ne varmistaa et oot legit eikä joku alennushuijari.",
    "how.step4.bullet1": "Näytä aktivoitu diili henkilökunnalle",
    "how.step4.bullet2": "Instant verificointi & hyväksyntä",
    "how.step5.title": "Maksa Puolet, Tunne Itsesi Kokonaiseksi",
    "how.step5.description": "Anna 50% siitä mitä normaalisti antasit ja kävele pois niinku se talousnero mitä oot. Arvioi kokemus ni meidän AI menee vielä creepimmäks siinä tietämisessä mitä haluat.",
    "how.step5.bullet1": "Maksa vaan 50% alkuperäisestä hinnasta",
    "how.step5.bullet2": "Arvioi kokemus parempaa AI:ta varten",
    "how.why.label": "Miksi Me Ei Olla Idiootteja",
    "how.why.heading": "Suunniteltu Laiskoja Ihmisiä Varten, Laiskoille Ihmisille",
    "how.why.description": "Me vihataan monimutkaisia juttuja yhtä paljon ku säkin. Ni me tehtiin tää niin yksinkertaseks, et se on periaatteessa loukkaus sun älykkyydelle.",
    "how.benefit1.title": "Nolla Aivosoluja Vaadita",
    "how.benefit1.description": "Ei saksia kupongeille, ei muistipalatsii koodeille, ei kalenterimuistutuksii vanhentumisvuosille. Vaan instant tyydytystä sun shoppailiriippuvuudelle.",
    "how.benefit2.title": "Nopeempi Ku Sun Exän Rebound",
    "how.benefit2.description": "Aktivoi alennukset nopeemmin ku ehdit sanoo 'taloudellinen vastuu.' Ei odottelua niinku oisit jossain DMV:ssä.",
    "how.benefit3.title": "AI Joka Oikeesti Ymmärtää Sut",
    "how.benefit3.description": "Meidän AI oppii sun maun paremmin ku sun terapeutti oppii sun traumat. Se ehdottaa diilejä mitä oikeesti haluat, ei randomii krääsää.",
    // Partners page
    "partners.hero.badge": "BISNESKUMPPANUUS",
    "partners.hero.headline1": "500+ Bisnestä Ei Voi Olla Väärässä",
    "partners.hero.headline2": "(Mut Sun Kilpailijat Voi Olla)",
    "partners.hero.subheadline": "",
    "partners.hero.body": "Siis oikeesti, samalla kun sun kilpailijat maksaa järjettömiä provisioita... meidän kumppanit nauraa matkalla pankkiin.",
    "partners.hero.cta.primary": "Hae Nyt",
    "partners.hero.cta.secondary": "Liity Jäseneksi",
    "partners.stats.activePartners": "Aktiivista Kumppania",
    "partners.stats.commissionFees": "Provisiomaksut",
    "partners.stats.avgIncrease": "Keskim. Kasvu",
    "partners.stats.qualityMembers": "Laadukkaita Jäseniä",
    "partners.signup.badge": "Nopea Startti",
    "partners.signup.headline": "Kirjaudu Nyt - Ei Hakemuksia!",
    "partners.signup.subheadline": "Luo bisnestilisi heti ja aloita onboarding välittömästi. Ei odottelua, ei pitkää hyväksymisprosessia.",
    "partners.signup.steps.step1.title": "Luo Tili",
    "partners.signup.steps.step1.description": "Kirjaudu heti bisnessähköpostilla ja perustiedoilla",
    "partners.signup.steps.step1.duration": "Vie 2 minuuttii",
    "partners.signup.steps.step2.title": "Aseta 50% Tarjoukset",
    "partners.signup.steps.step2.description": "Valitse mitkä palvelut saa 50% alennuksen (3x vuodessa per asiakas)",
    "partners.signup.steps.step2.action": "Määrittele tarjouksesi",
    "partners.signup.steps.step3.title": "Go Live",
    "partners.signup.steps.step3.description": "Lisää kuvat, menu, logo. Nopee verificointi, sit live!",
    "partners.signup.steps.step3.action": "Aloita asiakkaiden vastaanotto",
    "partners.signup.form.venueName": "Paikan Nimi",
    "partners.signup.form.venueNamePlaceholder": "Sun bisnesnimi",
    "partners.signup.form.city": "Kaupunki",
    "partners.signup.form.cityPlaceholder": "Missä sijaitset?",
    "partners.signup.form.email": "Sähköposti",
    "partners.signup.form.emailPlaceholder": "Bisnes-sähköpostiosoite",
    "partners.signup.form.button": "Hae Nyt",
    "partners.signup.form.validation": "Täytä kaikki kentät",
    "partners.signup.form.success": "Hakemus lähetetty! Ollaan yhteydessä pian.",
    "partners.signup.benefits.noApplication": "Ei Hakemusta Vaadita",
    "partners.signup.benefits.instantSetup": "Välitön Setuppi",
    "partners.signup.benefits.zeroCommission": "Nolla Provisiota",
    "partners.comparison.badge": "Matikka",
    "partners.comparison.headline": "Numerot Ei Valehtele",
    "partners.comparison.subheadline": "Katso tarkalleen paljon enemmän pidät Bargnilla vs perinteiset alustat. Spoileri: Se on paljon.",
    "partners.comparison.transactionValue": "Transaktion Arvo",
    "partners.comparison.transactionHelper": "Säädä nähdäksesi potentiaalisi ansiot",
    "partners.comparison.platformCommission": "Alustan Provisio",
    "partners.comparison.commissionHelper": "Tyypillinen range: 25-45%",
    "partners.comparison.traditional.title": "Perinteiset Alustat",
    "partners.comparison.traditional.subtitle": "UberEats, Wolt, jne.",
    "partners.comparison.bargn.title": "Bargn",
    "partners.comparison.bargn.subtitle": "Nolla Provisiota, Maksimi Profit",
    "partners.comparison.originalPrice": "Alkuperäinen Hinta",
    "partners.comparison.customerPays": "Asiakas Maksaa",
    "partners.comparison.off": "alennus",
    "partners.comparison.revenue": "Sun Tulot",
    "partners.comparison.platformTakes": "Alusta Ottaa",
    "partners.comparison.bargnTakes": "Bargn Ottaa",
    "partners.comparison.youKeep": "Sä Pidät",
    "partners.comparison.margin": "voittomarginaali",
    "partners.comparison.difference.title": "Sun Etu Bargnilla",
    "partners.comparison.difference.extraRevenue": "Extra Tulot Per Transaktio",
    "partners.comparison.difference.moreProfit": "Enemmän Voittoo",
    "partners.comparison.difference.description": "Per transaktio. Kerro tää sadoilla asiakkailla kuukaudessa.",
    // Campaign page
    "campaign.hero.badge": "🔥 40% TULONJAKO ✨",
    "campaign.hero.headline": "Tienaa Rahaa Samalla Kun Luot",
    "campaign.hero.subheadline": "40% Tulonjako • Ei BS:ää • Oikeaa Rahaa",
    "campaign.hero.description": "Kyllästyny saamaan palkkaa 'näkyvyydellä'? Me kirjaimellisesti heitämme rahaa sisällöntuottajille.",
    "campaign.hero.cta1": "Aloita Mun Tulovirta",
    "campaign.hero.cta2": "Opi Miten Me Maksetaan",
    "campaign.stats.revenueShare": "Tulonjako",
    "campaign.stats.activeCreators": "Aktiivista Tekijää",
    "campaign.stats.paidOut": "Maksettu Ulos",
    "campaign.stats.minPayout": "Minimimaksu",
    "campaign.goldRush.title": "Bargn Influensserien Kultaryntäys",
    "campaign.goldRush.description": "Plot twist: me oikeesti maksetaan meidän tekijöille. Ku muut firmat tarjoo sulle 'brändi kumppanuuksia' jotka on kolmen energiajuoman ja surullisen emojin arvoisia, me ollaan täällä jakamas oikeeta tuloa. Jokainen henkilö joka liittyy sun sisällön kautta? Saat 40% niiden tilausksuista. Ikuisesti. Joo, me sanottiin ikuisesti.",
    "campaign.goldRush.benefit1.title": "Oikea Tulonjako (Ei Kimblerahaa)",
    "campaign.goldRush.benefit1.description": "40% jokaisesta tilauksesta sun referraaleista menee suoraan sun tilille. Ei minimirajoja, ei 'maksetaan ku Jupiter on linjassa Marsin kans' hömppää. Vaan oikeeta rahaa oikeesta työstä.",
    "campaign.goldRush.benefit2.title": "Luova Kontrolli Joka Oikeesti Tarkottaa Jotain",
    "campaign.goldRush.benefit2.description": "Tee sisältöö joka sopii sun vibeen. Me ei micromanagoida sun luovuutta tai pakoteta sua sanomaan cringe corporate buzzwordeja. Sun yleisö luottaa suhun, ei meidän markkinointiosastoon.",
    "campaign.goldRush.benefit3.title": "Eksklusiivinen Pääsy (Koska Oot Spesiaali)",
    "campaign.goldRush.benefit3.description": "Eka diibs uusiin featureihin, suora linja meidän tiimiin, ja sisäpiiritietoo tulevista kampanjoista. Plus, sun oma personal dashboard seurataksesi ansioita real-timessa. Läpinäkyvyys on sexy.",
    "campaign.moneyTalk.title": "Rahapuhe (Meidän Lemppariaihe)",
    "campaign.moneyTalk.subtitle": "Ollaan rehellisiä - oot täällä rahojen takia. Tässä tea:",
    "campaign.moneyTalk.card1.title": "Jopa 40% Tulonjako",
    "campaign.moneyTalk.card1.description": "€8.8 kuukausitilaus = €3.52 sulle per referraali. €53 vuositilaus = €21.20 sulle. Matikkaa joka oikeesti toimii.",
    "campaign.moneyTalk.card2.title": "Ei Minimipaysoutia BS:ää",
    "campaign.moneyTalk.card2.description": "Jotku alustat saa sut odottaan et osut €100 et saat maksun. Me maksetaan €5 alkaen. Koska vuokra ei odota mielivaltaisia rajoja.",
    "campaign.moneyTalk.card3.title": "Nopeet Maksut (Niinku, Oikeesti Nopeet)",
    "campaign.moneyTalk.card3.description": "Viikoittaiset maksut suoraan sun pankkiin. Ei 'shekki on postissa' vibei. Me ei olla sun sketchy ex joka on sulle velkaa.",
    "campaign.contentIdeas.title": "Sisältöideoita Jotka Ei Saa Sua Cringee",
    "campaign.contentIdeas.subtitle": "Tässä inspoo joka ei saa sun seuraajia unfollaamaan sua:",
    "campaign.contentIdeas.idea1.title": "'Koitin Alennusappia Josta Kaikki Puhuu'",
    "campaign.contentIdeas.idea1.description": "Näytä aito reaktio siihen et löydät 50% alennukset sun lempipaikoista. Spoiler alert: tuut oleen shook.",
    "campaign.contentIdeas.idea2.title": "'Miten Säästän €500/kk Olematta Kitsas'",
    "campaign.contentIdeas.idea2.description": "Jaa sun oikeet säästöt ja flexaa ihmisille jotka vielä maksaa täyttä hintaa niinku ois 2019. Opettavaista ja vähän savage.",
    "campaign.contentIdeas.idea3.title": "'Testaan Onks Tää Alennusappi Oikeesti Legit'",
    "campaign.contentIdeas.idea3.description": "Dokumentoi sun eka kuukausi Bargnin kans. Spoiler: se on legit, ja sun yleisö haluu mukaan säästöihin.",
    "campaign.testimonials.title": "Mitä Meidän Creator Fam Sanoo",
    "campaign.testimonials.testimonial1.name": "Aino L., Lifestyle Creator (180k seuraajaa)",
    "campaign.testimonials.testimonial1.quote": "Tein €2,400 kolmessa ensimmäisessä kuussa vaan jakamalla jotain mitä oikeesti käytän päivittäin. Tulonjako ei oo vitsi - ne oikeesti maksaa mitä lupaavat. Paras kumppanuus ikinä.",
    "campaign.testimonials.testimonial2.name": "Ville K., Tech Reviewer (95k seuraajaa)",
    "campaign.testimonials.testimonial2.quote": "Vihdoin brändi joka ei kohtele tekijöitä niinku ilmasta mainostilaa. 40% tulonjako tarkottaa et voin keskittyy laatusisältöön sen sijaan et hustlaan monta pientä sponssii. Game changer.",
    "campaign.requirements.title": "Mitä Me Oikeesti Tarvitaan Sulta",
    "campaign.requirements.subtitle": "Ei mahdottomia standardeja, vaan oikeeta puhetta siitä mikä saa tän toimimaan:",
    "campaign.requirements.req1": "Joku some läsnäolo (joo, jopa 500 seuraajaa riittää)",
    "campaign.requirements.req2": "Aitoo sisältöö joka ei huuda 'ilmiselvä mainos'",
    "campaign.requirements.req3": "Asut Suomessa (sori, me ei tehdä maantieteellisiä sääntöjä)",
    "campaign.requirements.req4": "Voit laillisesti tehä sopimuksia (eli oot 18+ etkä kissa)",
    "campaign.process.title": "Miten Liittyy Rahaklubbiin",
    "campaign.process.subtitle": "Neljä askelta sun ja maksetun luovuuden välillä:",
    "campaign.process.step1.title": "Hae",
    "campaign.process.step1.description": "Täytä meidän lomake (se on lyhyempi ku sun viimenen Insta caption)",
    "campaign.process.step2.title": "Chattaa",
    "campaign.process.step2.description": "Nopee videopuhelu varmistaaksemme et sovitaan (me vast todennäköisesti sovitaan)",
    "campaign.process.step3.title": "Luo",
    "campaign.process.step3.description": "Tee sisältöö Bargnista sun tyylillä, sun tavalla",
    "campaign.process.step4.title": "Saa Maksu",
    "campaign.process.step4.description": "Katso sun pankkitilin kasvavan aina ku joku liittyy",
    "campaign.faq.title": "Kysymyksiä? Meillä On Kuitit",
    "campaign.faq.subtitle": "(Ja ne on vast rehellisempiä ku odotit)",
    "campaign.faq.q1": "Onks tää tulonjako juttu oikeesti totta vai vaan markkinointi BS:ää?",
    "campaign.faq.a1": "Se on totta AF. Me kirjaimellisesti annetaan sulle 40% jokaisesta tilauksesta sun referraaleista. Me on jo maksettu yli €50k tekijöille. Haluutsä kuitit? Meidän top creator teki €4.2k viime kuussa. Matikka ei valehtele.",
    "campaign.cta.title": "Valmiina Tienaamaan Oikeeta Rahaa?",
    "campaign.cta.description": "Liity 200+ tekijään jotka on tajunnu et oikeudenmukainen palkka on paljo parempi ku työskentely 'näkyvyydelle'",
    "campaign.cta.button": "Aloita Mun Tulovirta",
    // Blog page
    "blog.hero.badge": "BARGN BLOGI",
    "blog.hero.headline": "Tarinoita Jotka Merkitsee",
    "blog.hero.subheadline": "Meidän Yhteisöstä",
    "blog.featured.tag": "Pakko Lukea",
    "blog.featured.title": "10 Nerokasta Tapaa Maksimoida 50% Alennuksesi",
    "blog.featured.meta": "8 min lukuaika",
    "blog.categories.all": "Kaikki Julkaisut",
    "blog.categories.guides": "Alennusoppaat",
    "blog.categories.spotlights": "Kumppaninostot",
    "blog.categories.stories": "Menestystarinat",
    "blog.article1.title": "Miten Sarah Säästiivät €5,000 6 Kuukaudessa Bargnilla",
    "blog.article1.excerpt": "Oikea jäsen, oikeet säästöt, oikeet kuitit. Sarah muuttu köyhästä taloudellisesti fiksuksi.",
    "blog.article1.category": "Menestystarinat",
    "blog.article2.title": "Miksi Perinteiset Kuponkiappit Huijaavat Sua",
    "blog.article2.excerpt": "Kuuma takea: Ne 'tarjous' appit tekee rahaa susta ku luulet säästäväsi.",
    "blog.article2.category": "Alennusoppaat",
    "blog.article3.title": "50 Uutta Kumppania Liitty – Tässä Missä",
    "blog.article3.excerpt": "Me laajennetaan nopeemmin ku koskaan. Katso uudet paikat missä voit säästää.",
    "blog.article3.category": "Kumppaninostot",
    // Footer
    "footer.newsletter.title": "Uutiskirje (Ei Spämmiä, Pelkkää Vibeä)",
    "footer.newsletter.placeholder": "sun@email.com",
    "footer.newsletter.button": "Tilaa",
    "footer.links.privacy": "Tietosuoja",
    "footer.links.terms": "Käyttöehdot",
    "footer.links.cookies": "Evästekäytäntö",
    "footer.info.address": "Helsinki, Suomi",
    "footer.info.businessId": "Y-tunnus: 1234567-8",
    "footer.copyright": "© 2024 Bargn. Kaikki oikeudet pidätetään.",
    "footer.tagline": "Löydä. Säästä. Toista.",
    "chatWidget": "Kysy Bargn AI:lta",
    // 404 Page
    "404.headline": "Väärä Suunta, Oikea Appi",
    "404.subtext": "Sivu hukassa, diilit ei. Mennään takaisin kultasuoneen.",
    "404.cta": "Takaisin Kotiin",
    // Privacy Policy
    "privacy.intro": "Lakimiehet pakotti. Ota kahvia, tää on kuivaa.",
    "privacy.title": "Tietosuojakäytäntö",
    // Terms of Service
    "terms.intro": "Joo, sun täytyy lukee tää. Ei, me ei tykkää tästä myöskään.",
    "terms.title": "Käyttöehdot",
    // Cookie Policy
    "cookies.intro": "Ei suklaakeksi. Internet stalker tyyppiä.",
    "cookies.title": "Evästekäytäntö",
    // Cookie Consent Banner
    "cookieConsent.title": "Meidän Täytyy Puhuu Evästeistä (Tylsästä Lajista)",
    "cookieConsent.description": "Katso, meidän on laillisesti pakko kertoo et me käytetään evästeitä. Mut toisin ku sun ex, näillä evästeillä on oikeesti tarkoitus - tehdä sun kokemuksesta vähemmän paskaa. Voit vibaa kaikkien kans tai vaan välttämättömien. Sun valinta.",
    "cookieConsent.moreInfo": "Haluutsä koko legal tean?",
    "cookieConsent.learnMore": "Lue Evästekäytäntö",
    "cookieConsent.acceptAll": "Hyväksy Kaikki (Ollaan Cooljii)",
    "cookieConsent.rejectAll": "Vaan Välttämättömät (Nirso)",
    "cookieConsent.customize": "Anna Mun Valita",
    "cookieConsent.settingsTitle": "Evästeasetukset (Kontrollifrikeille)",
    "cookieConsent.essential.title": "Välttämättömät Evästeet (Ei Voi Sanoo Ei)",
    "cookieConsent.essential.description": "Nää pitää valot päällä. Ilman niitä appi ei kirjaimellisesti toimi. Sori not sori, oot jumis näiden kans.",
    "cookieConsent.analytics.title": "Analytiikkaevästeet (Ollaan Uteliaita)",
    "cookieConsent.analytics.description": "Auttaa meitä näkee mikä toimii ja mikä on paskaa. Ei henkilökohtaista dataa myydä, luvataan. Haluamme vaan tietää käyttääkö jengi oikeesti sitä nappia.",
    "cookieConsent.marketing.title": "Markkinointievästeet (Stalkkerit)",
    "cookieConsent.marketing.description": "Nää seuraa sua ympäri internettiä niinku sun yläastekrush. Ne näyttää mainoksia jotka voi oikeesti olla relevantteja sen sijaan et random paskaa.",
    "cookieConsent.savePreferences": "Tallenna Valintani",
    "cookieConsent.back": "Takaisin",
  },
  sv: {
    // Navigation
    home: "Hem",
    members: "Medlemmar",
    partners: "Partners",
    howItWorks: "Hur Det Fungerar",
    about: "Om Oss",
    blog: "Blogg",
    campaign: "Kampanj",
    letsGo: "Kör Igång",
    updateBanner: "Webbplatsen uppdateras",
    
    // Hero Section
    heroHeadline: "50% Rabatt På Allt",
    heroSubhead: "AI-drivna rabatter som faktiskt fungerar",
    heroText: "Gå med tusentals som knäckt koden för smart shopping. Vår AI lär sig dina preferenser och serverar personliga 50% rabatter på lokala hotspots.",
    heroDiscountRate: "Rabattsats",
    heroPartners: "Partners",
    heroSaved: "Sparat",
    
    // Members page
    membersHero: "Gå med 10K+ Legender Som Aldrig Betalar Fulla Priser",
    membersHeroSub: "",
    membersHeroDesc: "Välkommen till klubben där att betala fullt pris är basically olagligt. Vår AI är bokstavligen smartare än ditt ex och hittar deals som får din plånbok att dansa.",
    startSaving: "Börja Spara Nu",
    becomePartner: "Bli En Partner",
    happyMembers: "Nöjda Medlemmar",
    avgSavings: "Genomsnittligt Sparande",
    avgAnnualSavings: "Genomsnittligt Årligt Sparande",
    partnerOutlets: "Partner-Ställen",
    
    // Pricing
    pricingTitle: "Prissättning Som Inte Rånar Dig",
    pricingDesc: "Två alternativ: spara pengar månadsvis eller spara ännu mer pengar årligen. Oavsett vilket vinner du.",
    monthlyFlex: "Månadsflex",
    annualPower: "Årligt Power Move",
    bestValue: "Bästa Värdet",
    perMonth: "/månad",
    perYear: "/år",
    saveAnnually: "Spara €52.6 årligen",
    joinNow: "Gå Med Nu",
    cancelAnytime: "Avbryt när som helst",
    monthsFree: "2 månader GRATIS bonus",
    
    // Partners
    "partners.hero.badge": "AFFÄRSPARTNERSKAP",
    "partners.hero.headline1": "500+ Företag Kan Inte Ha Fel",
    "partners.hero.headline2": "(Men Din Konkurrent Kanske Har Det)",
    "partners.hero.body": "Titta, medan dina konkurrenter fortfarande betalar höga provisioner... skrattar våra partners hela vägen till banken.",
    "partners.hero.cta.primary": "Ansök Nu",
    "partners.hero.cta.secondary": "Gå Med Som Medlem",
    
    // Campaign
    "campaign.hero.badge": "🔥 40% INTÄKTSDELNING ✨",
    "campaign.hero.headline": "Tjäna Pengar Medan Du Skapar",
    "campaign.hero.subheadline": "40% Intäktsdelning • Inget BS • Riktiga Pengar",
    "campaign.hero.description": "Trött på att få betalt i 'exponering'? Vi kastar bokstavligen pengar på skapare som kan göra vår rabattapp viral. Inga följarkrav, inga själsdödande kontrakt, bara kalla hårda kontanter för kvalitetsinnehåll.",
    
    // FAQ
    faqTitle: "FAQ",
    faqHeading: "Har Du Frågor? Vi Har Svar",
    faqQ1: "Kan jag avsluta när jag vill?",
    faqA1: "Självklart! Avbryt när som helst, inga skuldkänslor eller konstiga exitenkäter. Vi är inte ditt kletiga ex.",
    faqQ2: "Hur fungerar denna magi?",
    faqA2: "Visa det Bargn-medlemskapet som VIP:en du är. Boom - 50% rabatt direkt. Inga kuponger, inget krångel, inget cap.",
    faqQ3: "Är jag fast i ett kontrakt?",
    faqA3: "Helvete nej! Vi är inte ett gym-medlemskap. Månad-till-månad eller årligen - ditt val. Avbryt när som helst, vi är fortfarande vänner.",
    
    // Cookie Consent
    "cookieConsent.title": "Vi Använder Cookies (För Din Skull, Inte Våran)",
    "cookieConsent.description": "Vi använder cookies för att förbättra din upplevelse. Du bestämmer vilka.",
    "cookieConsent.acceptAll": "Acceptera Alla",
    "cookieConsent.rejectAll": "Avvisa Alla",
    "cookieConsent.customize": "Anpassa",
    "cookieConsent.necessary": "Nödvändiga",
    "cookieConsent.necessary.description": "Dessa är obligatoriska. De låter sajten faktiskt fungera. Utan dem skulle ingenting funka.",
    "cookieConsent.analytics": "Analytiska",
    "cookieConsent.analytics.description": "Hjälper oss förstå vad folk klickar på så vi kan göra saker mindre suga.",
    "cookieConsent.marketing": "Marknadsföring",
    "cookieConsent.marketing.description": "Dessa följer dig runt internet som din crush från högstadiet. De visar annonser som faktiskt kan vara relevanta istället för slumpmässig skit.",
    "cookieConsent.savePreferences": "Spara Mina Val",
    "cookieConsent.back": "Tillbaka",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  // Detect browser language on mount
  useEffect(() => {
    const browserLang = navigator.language.split('-')[0];
    if (browserLang === 'fi' || browserLang === 'sv') {
      setLanguage(browserLang as Language);
    }
  }, []);

  // Update HTML lang attribute when language changes
  useEffect(() => {
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
